### PR TITLE
Call _refresh to ensure index is refreshed before getting the status

### PR DESCRIPTION
**Pull request by pib**
Without this call to RefreshIndex added, TestIndexStatus was failing for me because the refresh total was coming back as 0. Using ElasticSearch 1.5.1.

```
----------------------------------------------------------------------
FAIL: goes_test.go:773: GoesTestSuite.TestIndexStatus

goes_test.go:838:
    c.Assert(response.Indices, DeepEquals, expectedIndices)
... obtained map[string]goes.IndexStatus = map[string]goes.IndexStatus{"testindexstatus":goes.IndexStatus{Index:map[string]interface {}{"primary_size_in_bytes":115, "size_in_bytes":115}, Translog:map[string]uint64{"operations":0x0}, Docs:map[string]uint64{"deleted_docs":0x0, "num_docs":0x0, "max_doc":0x0}, Merges:map[string]interface {}{"total":0, "total_time_in_millis":0, "total_docs":0, "total_size_in_bytes":0, "current":0, "current_docs":0, "current_size_in_bytes":0}, Refresh:map[string]interface {}{"total":0, "total_time_in_millis":0}, Flush:map[string]interface {}{"total":0, "total_time_in_millis":0}}}
... expected map[string]goes.IndexStatus = map[string]goes.IndexStatus{"testindexstatus":goes.IndexStatus{Index:map[string]interface {}{"size_in_bytes":115, "primary_size_in_bytes":115}, Translog:map[string]uint64{"operations":0x0}, Docs:map[string]uint64{"num_docs":0x0, "max_doc":0x0, "deleted_docs":0x0}, Merges:map[string]interface {}{"current_docs":0, "current_size_in_bytes":0, "total":0, "total_time_in_millis":0, "total_docs":0, "total_size_in_bytes":0, "current":0}, Refresh:map[string]interface {}{"total":1, "total_time_in_millis":0}, Flush:map[string]interface {}{"total":0, "total_time_in_millis":0}}}
```

### CODE REVIEW

**Comment by jeromer** [comment]
Travis build seems to be broken with your changes. Could you please have a look ?

Thanks :)

**Comment by pib** [comment]
Oh wow, that is running a really old version of ElasticSearch (1.0.1, the current stable version is 1.6.0). It appears that older versions of ElasticSearch would record a refresh for an index as soon as it was created, whereas newer versions only record a refresh when one actually happens. The result of this is my test that manually runs refresh making the number of refreshes 2 on the old version of ElasticSearch.

Let me see if just using a 5 second timeout (the default refresh interval) will make it work the same in both versions.

**Comment by pib** [comment]
No, with 1.5.1 it never bumps the refresh count unless you manually tell it to refresh. So this is a difference between versions of ElasticSearch.

What's the proper way to test this between ES versions? It seems like the refresh count isn't really a valuable thing to be testing for a specific value on. Perhaps changing the assertion to check individual fields in the response?

**Comment by pib** [comment]
Also, can more recent versions of ElasticSearch be added into the Travis setup? Ideally 1.4.2, 1.5.1/2, and 1.6.0 would also be tested against.

**Comment by jeromer** [comment]
> What's the proper way to test this between ES versions? It seems like the refresh count isn't really a valuable thing to be testing for a specific value on. Perhaps changing the assertion to check individual fields in the response?

If the source of the problem is elasticsearch behaving differently between versions we do not have much choices. We have to test fields individually.

> Also, can more recent versions of ElasticSearch be added into the Travis setup? Ideally 1.4.2, 1.5.1/2, and 1.6.0 would also be tested against.

Sure can you update the travis configuration file in the repo ?

Thanks :)

**Comment by jeromer** [comment]
The build is still broken, due to commit bf23e36, see https://travis-ci.org/belogik/goes/jobs/68081911

**Comment by pib** [comment]
Yes, I'm aware it is still broken. I was working on getting the Travis config working as expected before fixing the actual ticket. Right now it's working on ES 1.5 and later and failing on earlier ES versions. I'll fix the test to be less brittle between versions now.

**Comment by jeromer** [comment]
Awesome !

**Comment by pib** [comment]
Ok, finally. It is actually working properly now. The post-1.3 versions of ES changed several things that the tests were relying on..

**Pull request merged**
